package password_manager;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'GrauWolf' at '5/6/22 1:05 PM' with Gradle 2.14.1
 *
 * @author GrauWolf, @date 5/6/22 1:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
